In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4], dtype = np.int64)

In [5]:
x.dtype

dtype('int64')

In [6]:
x.shape

(4,)

In [8]:
m = np.array([[2, 3, 4],[5,6,7]])

In [9]:
m.shape

(2, 3)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.random((2, 3))

array([[0.53417659, 0.16080433, 0.06861841],
       [0.39316207, 0.26731543, 0.7057897 ]])

In [17]:
y = np.array([[1,3,4,4], [2,3,4,56]])

In [18]:
y[1,3]

56

In [21]:
y[:, :3]

array([[1, 3, 4],
       [2, 3, 4]])

In [22]:
y > 2

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [23]:
y[y > 2]

array([ 3,  4,  4,  3,  4, 56])

In [33]:
b = np.array([[1,3,4,4,5],[2,3,4,56,5]])

In [34]:
b.shape

(2, 5)

In [35]:
b.flatten()

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [36]:
b.T

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

In [37]:
b.reshape((10, 1))

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [39]:
b.resize((10, 1))

In [40]:
b

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [41]:
v = np.array([9, 10])
w = np.array([11, 12])

In [42]:
v + w

array([20, 22])

In [43]:
np.add(v, w)

array([20, 22])

In [44]:
v - w

array([-2, -2])

In [45]:
np.subtract(v, w)

array([-2, -2])

In [46]:
v * w

array([ 99, 120])

In [47]:
np.multiply(v, w)

array([ 99, 120])

In [48]:
np.dot(v, w)

219