In [1]:
import numpy as np

In [3]:
np.unique([[3,3,3], [1,3,4], [7, 1, 3]])

array([1, 3, 4, 7])

In [5]:
 Z = np.array([92, 13, 44, 555, 1, -3])

In [19]:
np.flip(Z)[4]

13

In [7]:
a = np.ones(5)
b = np.full(5, 2)

In [8]:
np.dot(a, b)

10.0

In [22]:
a = np.array([[0, 9, 19, 13], [1, 20, 5, 13], [12, 11, 3, 4]])
b = np.array([[2, 0, 0, 0], [1, 2, 2, 0], [2, 1, 1, 0], [0, 0, 1, 1]])

In [24]:
c = np.dot(a, b)
c

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [11]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
np.mean(b)

4.875

In [14]:
from scipy import linalg

In [15]:
X = np.array([[6, 0, 3], [0, -1, 2], [12, 3, 0]])
linalg.det(X)

0.0

In [17]:
X = np.array([[1, -1, -1, 0], [-1, 2, -1, -1], [-1, -1, 2, -1], [0, -1, -1, 1]])
linalg.eig(X)[0]

array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j])

In [18]:
X = np.array([[2, 4, 0, 4, 1], [2, 4, 1, 1, 0], [1, 1, 1, 2, 2], [0, 1, 3, 2, 4], [2, 2, 2, 0, 2]])
linalg.inv(X).trace()

2.700000000000001

In [21]:

foo = np.array([[0,9,19,13],[1,20,5,13],[12,11,3,4]])
bar = np.array([[2,0,0,0],[1,2,2,0],[2,1,1,0],[0,0,1,1]])
foobar = np.dot(foo,bar)
foobar

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])